version: '2'

services:
        postgres:
                build: postgres
                restart: always
                ports:
                        - 5432:5432

        tomcat:
                build: tomcat
                ports:
                        - 8080:8080
                links:
                        - postgres:postgres
