#!/bin/bash
set -e

#CREATE USER tede SUPERUSER INHERIT CREATEDB CREATEROLE;
#CREATE DATABASE dspace;
#GRANT ALL PRIVILEGES ON DATABASE dspace TO tede;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	ALTER USER tede WITH ENCRYPTED PASSWORD '123456';
EOSQL
